language: generic
sudo: required
dist: xenial
install:
  - sudo apt-get update
  - sudo apt-get install -y bc binfmt-support bzip2 fakeroot gcc gcc-arm-linux-gnueabihf git gnupg make parted qemu-user-static wget xz-utils zip debootstrap sudo dirmngr bison flex libssl-dev
  - gpg --keyserver hkp://keys.gnupg.net --recv-keys 38DBBDC86092693E
  - gpg --keyserver hkp://keys.gnupg.net --recv-keys 87F9F635D31D7652
script:
  - while true ; do echo "Still building" ; sleep 60 ; done &
  - echopid=$!
  - make all V=mark-two BOOT=eMMC JOBS=2 > (tee build.log |grep '>>>')
  - kill ${echopid}
  - tail -50 build.log
